In [1]:
import numpy as np

### 1.1. Установить, какие произведения матриц  𝐴𝐵  и  𝐵𝐴  определены, и найти размерности полученных матриц

#### б)

In [2]:
a = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
b = np.array([[3, 2, 1], [6, 9, 10], [7, 8, 9], [4, 1, 6], [3, 8,10]])
print(f'Матрица:\n{a}')
print(f'Матрица:\n{b}')

Матрица:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Матрица:
[[ 3  2  1]
 [ 6  9 10]
 [ 7  8  9]
 [ 4  1  6]
 [ 3  8 10]]


In [24]:
c = np.dot(a, b)
print(f'Матрица c = a*b :\n{c}')
print(f'размерность результирующей матрицы c:\n{c.shape}')

Матрица c = a*b :
[[ 67  88 122]
 [182 228 302]]
размерность результирующей матрицы c:
(2, 3)


#### в)

In [25]:
a = np.array([[1, 2, 3], [6, 7, 8], [3, 2, 1], [8, 7, 6], [4, 5, 2], [2, 3, 8], [9, 4, 1], [6, 3, 1]])
b = np.array([[3, 2, 1, 4, 1, 6, 7, 2], [3, 0, 1, 4, 5, 6, 3, 3], [4, 2, 2, 0, 1, 6, 8, 9]])
print(f'Матрица:\n{a}')
print(f'Матрица:\n{b}')

Матрица:
[[1 2 3]
 [6 7 8]
 [3 2 1]
 [8 7 6]
 [4 5 2]
 [2 3 8]
 [9 4 1]
 [6 3 1]]
Матрица:
[[3 2 1 4 1 6 7 2]
 [3 0 1 4 5 6 3 3]
 [4 2 2 0 1 6 8 9]]


In [26]:
c = np.dot(a, b)
print(f'Матрица c = a*b :\n{c}')
print(f'размерность результирующей матрицы c:\n{c.shape}')

Матрица c = a*b :
[[ 21   8   9  12  14  36  37  35]
 [ 71  28  29  52  49 126 127 105]
 [ 19   8   7  20  14  36  35  21]
 [ 69  28  27  60  49 126 125  91]
 [ 35  12  13  36  31  66  59  41]
 [ 47  20  21  20  25  78  87  85]
 [ 43  20  15  52  30  84  83  39]
 [ 31  14  11  36  22  60  59  30]]
размерность результирующей матрицы c:
(8, 8)


#### г)

In [27]:
a = np.array([[1, 2, 3, 4], [6, 8, 3, 1], [7, 4, 5, 2], [2, 9, 4, 1]])
b = np.array([[6, 8, 3, 1], [2, 9, 4, 1], [6, 1, 1, 0], [1, 2, 3, 4]])
print(f'Матрица:\n{a}')
print(f'Матрица:\n{b}')

Матрица:
[[1 2 3 4]
 [6 8 3 1]
 [7 4 5 2]
 [2 9 4 1]]
Матрица:
[[6 8 3 1]
 [2 9 4 1]
 [6 1 1 0]
 [1 2 3 4]]


In [28]:
c = np.dot(a, b)
print(f'Матрица c = a*b :\n{c}')
print(f'размерность результирующей матрицы c:\n{c.shape}')

Матрица c = a*b :
[[ 32  37  26  19]
 [ 71 125  56  18]
 [ 82 101  48  19]
 [ 55 103  49  15]]
размерность результирующей матрицы c:
(4, 4)


### 1.2. Найти сумму и произведение матриц  𝐴  и  𝐵.

In [29]:
A = np.array([[1, -2], [3, 0]])
B = np.array([[4, -1], [0, 5]])

In [30]:
C = A + B
C

array([[ 5, -3],
       [ 3,  5]])

In [31]:
C2 = np.dot(A,B)
C2

array([[  4, -11],
       [ 12,  -3]])

### 1.3. Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию  3𝐴−2𝐵+4𝐶  для матриц

<img src='task_3.png' width=400px>

In [7]:
a3 = np.array([[1, 7], [3, -6]])
b3 = np.array([[0, 5], [2, -1]])
c3 = np.array([[2, -4], [1, 1]])

In [8]:
d = 3*a3 - 2*b3 + 4*c3
d

array([[ 11,  -5],
       [  9, -12]])

<img src='task_4.png' width=400px>

In [9]:
a4 = np.array([[4, 1], [5, -2], [2, 3]])
a4

array([[ 4,  1],
       [ 5, -2],
       [ 2,  3]])

In [10]:
c = np.dot(a4,a4.T)
c

array([[17, 18, 11],
       [18, 29,  4],
       [11,  4, 13]])

In [11]:
d = np.dot(a4.T,a4)
d

array([[45,  0],
       [ 0, 14]])

### 2.1. Вычислить определитель

#### a)

In [38]:
x=5
a = np.array([[np.sin(x), -np.cos(x)], [np.cos(x), np.sin(x)]])
print(f'Матрица a:\n{a}')

Матрица a:
[[-0.95892427 -0.28366219]
 [ 0.28366219 -0.95892427]]


In [40]:
print(f'Определитель матрицы a:\n{np.linalg.det(a)}')

Определитель матрицы a:
1.0


#### б)

In [41]:
a = np.array([[4, 2, 3], [0, 5, 1], [0, 0, 9]])
print(f'Матрица a:\n{a}')

Матрица a:
[[4 2 3]
 [0 5 1]
 [0 0 9]]


In [42]:
print(f'Определитель матрицы a:\n{np.linalg.det(a)}')

Определитель матрицы a:
180.0


#### в)

In [43]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f'Матрица a:\n{a}')

Матрица a:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [45]:
print(f'Определитель матрицы a:\n{np.linalg.det(a):.0f}')

Определитель матрицы a:
0


### 2.3. Доказать, что матрица 𝐴 вырожденная.

In [46]:
a = np.array([[-2, 7, -3], [4, -14, 6], [-3, 7, 13]])
print(f'Матрица a:\n{a}')

Матрица a:
[[ -2   7  -3]
 [  4 -14   6]
 [ -3   7  13]]


#### Матрица называется вырожденной если её определитель равен нулю.

In [47]:
print(f'Определитель матрицы a:\n{np.linalg.det(a):.0f}')

Определитель матрицы a:
0


#### Следовательно матрица вырожденная.

### 2.4. Найти ранг матрицы.

#### а)

In [21]:
a6 = np.array([[1, 2, 3], [1, 1, 1], [2, 3, 4]])

In [22]:
r = np.linalg.matrix_rank(a6)
r

2

#### б)

In [23]:
a7 = np.array([[0, 0, 2, 1], [0, 0, 2, 2], [0, 0, 4, 3], [2, 3, 5, 6]])
r2 = np.linalg.matrix_rank(a7)
r2

3